package Model;
// Generated May 11, 2020 11:33:32 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BookInfo generated by hbm2java
 */
public class BookInfo  implements java.io.Serializable {


     private String bookid;
     private String title;
     private String publishingHouse;
     private Date dateOfPublication;
     private String author;
     private Integer pages;

    public BookInfo() {
    }

	
    public BookInfo(String bookid) {
        this.bookid = bookid;
    }
    public BookInfo(String bookid, String title, String publishingHouse, Date dateOfPublication, String author, Integer pages) {
       this.bookid = bookid;
       this.title = title;
       this.publishingHouse = publishingHouse;
       this.dateOfPublication = dateOfPublication;
       this.author = author;
       this.pages = pages;
    }
   
    public String getBookid() {
        return this.bookid;
    }
    
    public void setBookid(String bookid) {
        this.bookid = bookid;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPublishingHouse() {
        return this.publishingHouse;
    }
    
    public void setPublishingHouse(String publishingHouse) {
        this.publishingHouse = publishingHouse;
    }
    public Date getDateOfPublication() {
        return this.dateOfPublication;
    }
    
    public void setDateOfPublication(Date dateOfPublication) {
        this.dateOfPublication = dateOfPublication;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Integer getPages() {
        return this.pages;
    }
    
    public void setPages(Integer pages) {
        this.pages = pages;
    }




}


