package Model;
// Generated May 11, 2020 11:33:32 AM by Hibernate Tools 4.3.1



/**
 * BookCategory generated by hbm2java
 */
public class BookCategory  implements java.io.Serializable {


     private String categoryId;
     private String categoryName;

    public BookCategory() {
    }

	
    public BookCategory(String categoryId) {
        this.categoryId = categoryId;
    }
    public BookCategory(String categoryId, String categoryName) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
    }
   
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }




}


