package Model;
// Generated May 11, 2020 11:33:32 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Checkinout generated by hbm2java
 */
public class Checkinout  implements java.io.Serializable {


     private String status;
     private String client;
     private String book;
     private Date date;
     private String operationCategory;

    public Checkinout() {
    }

	
    public Checkinout(String status) {
        this.status = status;
    }
    public Checkinout(String status, String client, String book, Date date, String operationCategory) {
       this.status = status;
       this.client = client;
       this.book = book;
       this.date = date;
       this.operationCategory = operationCategory;
    }
   
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getClient() {
        return this.client;
    }
    
    public void setClient(String client) {
        this.client = client;
    }
    public String getBook() {
        return this.book;
    }
    
    public void setBook(String book) {
        this.book = book;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getOperationCategory() {
        return this.operationCategory;
    }
    
    public void setOperationCategory(String operationCategory) {
        this.operationCategory = operationCategory;
    }




}


